### ISSUE TITLE
11.3 void Pointers :: Interrogation

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#11]
This is something that I am still puzzled about after reading the chapter.
You discuss functions with void pointer type definitions.
The example shows that you can convert void pointers to other pointers before manipulating them.
If you know the types of pointers in the first place, why would you not want to declare it in the types of the calling function?
If you can add a line or two on why you would want to declare void pointers and coerce them immediately to another pointer, that would be amazing.
(If for any reason you don't have the time or don't think it makes sense, feel free to close without explaning, I just thought you might want to know).

**Comment by beejjorgensen** [comment]
I modded it to this... LMK if there's more I can do on this front... if that helps or not.

---------------------

Look at how versatile `memcpy()` is! If you have a pointer to a source and a pointer to a destination, and you have the number of bytes you want to copy, you can copy _any type of data_.

Imagine if we didn't have `void*`. We'd have to write specialized `memcpy()` functions for each type:

``` {.c}
memcpy_int(int *a, int *b, int count);
memcpy_float(float *a, float *b, int count);
memcpy_double(double *a, double *b, int count);
memcpy_char(char *a, char *b, int count);
memcpy_unsigned_char(unsigned char *a, unsigned char *b, int count);

// etc... blech!
```

Much better to just use `void*` and have one function that can do it all.

That's the power of `void*`. You can write functions that don't care about the type and is still able to do things with it.

**Comment by happysalada** [comment]
Ok so that means that inside the function then there will be some way to know which type of pointer we are talking about right?
My question becomes, if a function takes any type of pointer, how will it know how to coerce it?
Will you be passing a flag to your function to know?
memcopy(intpoint, intpoint, count, "int")
Or can you check the type of the pointer that is passed? So that you can coerce it to char* or int* as needed?

**Comment by beejjorgensen** [comment]
Right--these are good questions for sure.

There are basically two cases:

1. The function is going to do something byte-by-byte, like sending data over a network or copying data. C allows you to make a pointer to anything a `char*` and then access the individual bytes of that object, no matter the type. So `memcpy()` casts them to `char*` and copies however many bytes the caller specified.
2. Another function is calling a function you gave it (a callback) and it doesn't know the types of the data its passing you. But you do. An example is with the comparison function for `qsort()`. `qsort()` passes a couple `void*`s to your callback (since it doesn't know what type of data it's sorting) and your callback converts them into the proper type (since you know what type of data you're sorting).

I'll add more to this effect. Does that cover it?

(Really appreciate this feedback!)

**Comment by happysalada** [comment]
Absolutely! This is exactly what I was looking for! ❤️
